"""empty message

Revision ID: 14cdac1d125f
Revises: 27ae6db1cff5
Create Date: 2021-04-03 17:09:47.966037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cdac1d125f'
down_revision = '27ae6db1cff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderDetails', schema=None) as batch_op:
        batch_op.drop_column('auth_id')

    # ### end Alembic commands ###
