"""empty message

Revision ID: 27ae6db1cff5
Revises: 35e3ed0d32a0
Create Date: 2021-04-01 13:20:11.196737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ae6db1cff5'
down_revision = '35e3ed0d32a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_auth')
    op.drop_table('status')
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_auth_username'), ['username'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_cat_name'), ['cat_name'])

    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_item_item_name'), ['item_name'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_item_item_name'), type_='unique')

    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_cat_name'), type_='unique')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_auth_username'), type_='unique')

    op.create_table('status',
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('status_type', sa.VARCHAR(length=15), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('_alembic_tmp_auth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='uq_auth_phone'),
    sa.UniqueConstraint('username', name='uq_auth_username')
    )
    # ### end Alembic commands ###
