"""empty message

Revision ID: 35e3ed0d32a0
Revises: b96ce298921a
Create Date: 2021-03-25 11:24:56.130862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e3ed0d32a0'
down_revision = 'b96ce298921a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_orders')
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_auth_phone'), ['phone'])
        batch_op.create_unique_constraint(batch_op.f('uq_auth_username'), ['username'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_cat_name'), ['cat_name'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_item_item_name'), ['item_name'])

    with op.batch_alter_table('orderDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.String(length=100), nullable=True))
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.TEXT(length=100), nullable=True))
        batch_op.drop_column('items')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_item_item_name'), type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_cat_name'), type_='unique')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_auth_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_auth_phone'), type_='unique')

    op.create_table('_alembic_tmp_orders',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('auth_id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('items', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.TEXT(length=10), nullable=False),
    sa.Column('address', sa.TEXT(length=100), nullable=False),
    sa.Column('pickup_date', sa.DATETIME(), nullable=False),
    sa.Column('pickup_slot', sa.TEXT(length=50), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['auth.id'], ),
    sa.ForeignKeyConstraint(['items'], ['item.id'], name='fk_orders_items_item'),
    sa.ForeignKeyConstraint(['vendor_id'], ['auth.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
