"""empty message

Revision ID: 6a1da20cdcc3
Revises: 14cdac1d125f
Create Date: 2021-04-06 17:24:39.716402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1da20cdcc3'
down_revision = '14cdac1d125f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amt', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.drop_column('total_amt')

    # ### end Alembic commands ###
